[eye]
distance = 8      # Distance between the two eyes

[eye.left]
width = 32         # Default width of the left eye
height = 32        # Default height of the left eye
roundness = 8      # Default roundness of the left eye

[eye.right]
width = 32         # Default width of the right eye
height = 32        # Default height of the right eye
roundness = 8      # Default roundness of the right eye

[color]
# if screen mode is 1 bit it will be default to black and white
#bg = "yellow"      # Apply only for color screens
#eye = "red"	       # Apply only for color screens